name: studymate_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  get_storage: ^2.1.1
  google_fonts: ^6.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  uuid: ^4.2.1
  flutter_card_swiper: ^7.0.2
  syncfusion_flutter_charts: ^29.2.4
  lottie: ^3.1.0
  fluentui_system_icons: ^1.1.226
  font_awesome_flutter: ^10.7.0
  flutter_local_notifications: ^19.2.0
  timezone: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.7
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/empty.json
    - assets/lottie/success.json
